#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "-----------------푸시 테스트--------------------"

FORBIDDEN_HTTPS_URL="https://github.com/doran-front/test-frontend.git" # insert your remote url (https)
FORBIDDEN_REF="refs/heads/main" # insert branch ref

ARR_GIT_PARAMS=($(echo $HUSKY_GIT_PARAMS))
ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))

remote=${ARR_GIT_PARAMS[0]}
url=${ARR_GIT_PARAMS[1]}

local_ref=${ARR_GIT_STDIN[0]}
remote_ref=${ARR_GIT_STDIN[2]}

if [ "$url" != "$FORBIDDEN_HTTPS_URL" ]
then
    exit 0
fi

if [ "$remote_ref" == "$FORBIDDEN_REF" ]
then
    echo "DO NOT PUSH IT MAIN"
    exit 1
fi

exit 0